---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homelab-private
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@github.com/kamillw23/homelab-private
  ref:
    branch: main
  secretRef:
    name: homelab-private-deploy-key
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homelab-private
  namespace: flux-system
spec:
  interval: 10m
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-private
  decryption:
    provider: sops
    secretRef:
      name: sops-age
