---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant
resources:
  - ../../../base/home_assistant
patches:
  - target:
      kind: Ingress
      name: home-assistant
    path: patch-ingress.yaml

  - target:
      kind: Deployment
      name: home-assistant
    path: patch-deployment.yaml
