---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  rules:
    - host: "homelab"
      http:
        paths:
          - path: "/homelab"
            pathType: Prefix
            backend:
              service:
                name: homepage
                port:
                  number: 8123
