---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: zigbee2mqtt
spec:
    interval: 10m
    url: https://charts.zigbee2mqtt.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: zigbee2mqtt
spec:
    interval: 5m
    targetNamespace: zigbee2mqtt
    chart:
        spec:
            chart: zigbee2mqtt
            version: '2.9.2'
            sourceRef:
                kind: HelmRepository
                name: zigbee2mqtt
                namespace: fhome-assistant
            interval: 10m
    valuesFrom:
        -   kind: ConfigMap
            name: z2m-statefulset
            valuesKey: statefulset.yaml
        -   kind: ConfigMap
            name: zz2m-zigbee2mqtt
            valuesKey: zigbee2mqtt.yaml
        -   kind: Secret
            name: z2m-devices
            valuesKey: devices.yaml

    values: {}
