---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      initContainers:
        - command:
            - sh
            - -c
            - |
              cp /mnt/raw-secrets/users /mnt/writable-secrets/users
              chown 1883:1883 /mnt/writable-secrets/users
              chmod 700 /mnt/writable-secrets/users
              mosquitto_passwd -U /mnt/writable-secrets/users
          image: eclipse-mosquitto:latest
          imagePullPolicy: Always
          name: prepare-credentials-file
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /mnt/raw-secrets
              name: credentials-raw
              readOnly: true
            - mountPath: /mnt/writable-secrets
              name: credentials
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:latest
          ports:
            - containerPort: 1883
            - containerPort: 9001
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          livenessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: mosquitto-pvc
              mountPath: /mosquitto/data
            - name: credentials
              mountPath: /mosquitto/users/
              subPath: users
              readOnly: true
      volumes:
        - name: mosquitto-pvc
          persistentVolumeClaim:
            claimName: mosquitto-pvc
        - name: configuration
          configMap:
            name: mosquitto-config
        - name: credentials-raw
          secret:
            secretName: mosquitto-users
            defaultMode: 0440
        - name: credentials
          emptyDir: {}
