apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt
type: Opaque
data:
    secret.yaml: ENC[AES256_GCM,data:KzPsNM/QidIV61wGq4vFesK045ke6fNDLpBPm7MzFf4g35KHpNBrUeMr8cH+lrLpNu2O5WeGCFPbBpvf1ujMF2T+0JdItUd+/qa5VuyBO2QvivMqLjHkJU0amBg=,iv:Nyrwi8e1roR88hBuzc9dDfEVaRYn5PBtuXQ5m324jWQ=,tag:ZGdIkmvbJDhPTptbPzJv3w==,type:str]
sops:
    age:
        - recipient: age1rn9025gh9wcfwwuvde22hjhwle66w6qxrz6raxl28ed9r0rwsd0s5zd8fv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSb3gxWkh6dnBpbDRqTTdS
            YkJZQThuTlZzWlI1L1dTY3o0OE43OTNOY0JzCkYwRkhHVnlaeE5sR2VQYmZ3WExx
            WE8xS0pVSlVHSWRRS0x6VDd5eXFUakkKLS0tIE5RbC9zNXBidVMvTTB2aG9iK3N4
            S2dRUmlXT0pWWDhrMnFXR0xsTmtEdDQKlLQpofUs+QRpn9ZqeAcLThSw69f3Odze
            /BK5IgnEVfdh15d8dgs8MZqDugPC0wth2FwSKtlMtS8Ddy+MWia+cQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-22T20:44:39Z"
    mac: ENC[AES256_GCM,data:FVtKsILWebZoFz25qTwLXDZxh0Hzvez5o217DydcJrwsUcDotC3D3b7tfS1pxNzf9lQziUN702UmwWTAIsumUoZUfusB/Iz/zpBVTCwtxo7AHLvu2muctYBnQg6OAhw/xFYHqhQDOrslzDDopeZkaDo2MGrk571VkXZJnM1dLnk=,iv:Bn5+1mrN577kh58MMHDXsV+Hbd3J1tQQP7Oc7hAnmhw=,tag:bsAGAJhgQ8T6DU51RvVK2g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
