apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt
type: Opaque
data:
    secret.yaml: ENC[AES256_GCM,data:2OeFMTvfUfQ/W6isjVX78LZW1eulzeYdK0w/X/lXbQS74ajEEipzvZ5EDY/9Fz4B1QIKqsNtB8Gy12vHdliJUhLR9clBStW8PKO00B49H6W0qKGME4zg5kERRw==,iv:iNacxoYFhmIAmmFxJ4Yls1k9A2AEhg097nBe12JBH3U=,tag:1QKRRhS27FWt2aGM3vfrCA==,type:str]
sops:
    age:
        - recipient: age1rn9025gh9wcfwwuvde22hjhwle66w6qxrz6raxl28ed9r0rwsd0s5zd8fv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWVU5VUt2NkFaWC9hWmhE
            MVlLL1NJUWVUNGhCeWxEbVZUanNWY0o5S2xBCnZiU2xxV1ZTQkZDUytoUk9DSHpE
            aXFHZEdKQnNvQlM4c01LZU9FTEM2azAKLS0tIGRlL2V6QWpBVDJKRkhIOG1FVTBs
            YkhLS3V1SnBQRkdzTi9LR2hpNUFCaFUK9cUgNXwm81rVC9iedM+YHPLG79dKHH7D
            dtjlDWk/IdVZtZdyLXlkR4Je306WwjpULtXCgvQIMFXuzG4ju4SU+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-22T20:26:45Z"
    mac: ENC[AES256_GCM,data:3PGtqPsKIqB5QvM/JFCyuEtwXdArrSiz5QefFypvsGFDxyKTVj0RuK8K6xmDNK+SgsRaucxAd72YYRwhRBVMe4q53UnMF7kG1aeKzGnObXYZ+qRWoDfXjVw0SLTMLtJI/ek1S6aO9pte+1EvHmgRQbxD225GCCdCTl1mnlIp7ME=,iv:0TfeeOlFaTQYVGmgjErc/sRm3UlanNoFnHFdOYj/AMk=,tag:iVvQwBS0Y16DQi+LgAYkQw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
