apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt
type: Opaque
stringData:
    secret.yaml: ENC[AES256_GCM,data:U+uMglYmwmPNvKUGQ0mCrbTTMcalqyHZgSZMNzHImisgyGzGN92XT39Gf3FSV46jAtWctX0vWIcGeo+nWhqZagYCJxbp8a1524FNl6ftlKPtDA8IarytN9UPUw==,iv:ejjjRtiTH2dK9RTb6oCc8Ubqgt3c+EHhGU/F0T5BG7Q=,tag:acZMCWgFHvwzH1qR/vmJKg==,type:str]
sops:
    age:
        - recipient: age1rn9025gh9wcfwwuvde22hjhwle66w6qxrz6raxl28ed9r0rwsd0s5zd8fv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UVRCZmhGbU9JNW1UVUxI
            QTR3V1d5RkV0OWs2TVBER0xrY25XdVRxZlRnCjdDSE01YmlUa3NVMitYOW83ZDBk
            eWZjN3Rab1U4aXNCNUJVQ3dnU3Y0bkUKLS0tIHVtbVFsVDFITFFmZXZMbWlRMm4z
            TG9uSW1QOW45U0JXL2hhR2VSTDczL3cKy8rA2njGuSfli8KEqUcU4v6bwmbS5AyG
            SY1Z02e3XibUs3e53nu22ddCqavWE1uGorQ+YPGfxD980R/bP0Beuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-22T20:49:04Z"
    mac: ENC[AES256_GCM,data:uQ7K5LB+7LVWUqqHUGtnsmZG05uFoadoq6rOnyY+92cIkyPtnbJCQnINrHLBk1c8FMVyvABVbzSAgmpa8sYX5dO625ZBmS96I2Z/dsnIcreYAQ/JHrbKOBNbOHVnegWcf/dh6xIG6Oz33auE1mC+5q6kDWHbrMYsyGXpCS/PR9w=,iv:f9AQCjxLLLC0URJJ/zwwrTJkRwff1+VLWnlfzqLU3No=,tag:ozgW0EO81D7dIS5MbubTeg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
