apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources:
  - namespace.yaml
  - service_account.yaml
  - config_map.yaml
  - cluster_role.yaml
  - cluster_role_binding.yaml
  - deployment.yaml
  - ingress.yaml
  - service.yaml
