apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  values:
    grafana.ini:
      server:
        domain: homelab
        root_url: "%(protocol)s://%(domain)s:%(http_port)s/monitoring/"
        serve_from_sub_path: true
