---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |
    persistence true
    persistence_location /mosquitto/data/

    # Security
    allow_anonymous false
    password_file /mosquitto/config/users

    listener 1883 0.0.0.0
