---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      securityContext:
        fsGroup: 1883
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:latest
          args:
            - "/usr/sbin/mosquitto"
            - "-c"
            - "/mosquitto/config/mosquitto.conf"
          volumeMounts:
            - name: configuration
              mountPath: /mosquitto/config/
            - name: credentials
              mountPath: /mosquitto/users/
              subPath: users
              readOnly: true
      volumes:
        - name: configuration
          configMap:
            name: mosquitto-config
        - name: credentials
          secret:
            secretName: mosquitto-users
            defaultMode: 0440
