apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-users
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:doiVsfvSVuJJL+TblMsyqXA9wlJplPCaValmqjjL94vzQHZIwk/YExTEi5WMJsr2ct5HyJ7bzxnG4VCohiBKHensiWpWQwayWmCghjam6YrbkmHPsr+P9FUUiXMEA2pRbsk1Lou0GB7KiTmb+9Fdd3aN4R/c34FKn4QfOGqqvkpRAob0LR4PqyosAQCMaON1SznLcF1XJruuiGNGlqfVRXIa4F1qA+X3dmeR/CnFXMxjM2Fyjojk74iVhw9mtA4wSxmZEnhRQyE99+sYSNf/bLTKAjzo/SGO7S0CtpVub03q9yt5CtWZlGwFSdlGkZ/mr8qZztui0dW0SxP5ewwkC8Lr53QlGW/jsP4zl5OF4ZZZmtvnCwQlFdexzY4oV+B/NKFkEHMnLLyc2AnibcVTHfA6+6Cd86wpgIXVTROR7mC2RJN+426Kprxs4dIYT6vNZMhmqq9XzVfE6ds8wILI7Puw3CBWI70/MtwZRIWR+/gp23Vaf76WMdRwThBij7KxnqDzl2JIRkbwUQIwwuaCtmckjAkRWxNkJSOVy1bVleLUtBQOYLIp3N1vaBdwwLih15b3SCS5qxVU0/Enx/9ro9LAXB9FSAR2eM0IkIVgW5+yY9PwptWRG7p3DQ8wzKTF8e+cpNgQj/vEqGv29EGBGJymjifhVoyPbJd8BOvMEXf4LvySZTKnWbg/pQoqDnqIkETZAQsnXImw93C+Z5w53xZiH9FtOKX31qIc/HRo6//g7Pofbx93BCitkb5TPdaE8imvIeKN328Mmqk9u7w=,iv:6sdrpY++8hFzJwGEdmB0t+92ajQwyTZ0gxFNb14S/Fw=,tag:qX05vzypbQaQTZXopyJl2Q==,type:str]
sops:
    age:
        - recipient: age1rn9025gh9wcfwwuvde22hjhwle66w6qxrz6raxl28ed9r0rwsd0s5zd8fv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTHFPUWhORGxhWHZyeTVK
            VXRIVmIyRmtYWEJDT254MXBReXYrZC95M1RNCmRtNzFEdzJ4bjZPQ3RHcCtod0R5
            K2FVRTRWdUJqbUdSVlFvS1ZqbjZFNjQKLS0tIEp2UlZ6eFI4WXEzTGdCSU4rbGty
            aDB5c1pRT1IzR3JyK2NCVmZCWml3dTAKfDAK2QVbcPn3LzFsvbC9aD8lLueHShQe
            i0cEfWWR9l+SGpeC9Qq4xPRD8vT0I0VXBacORSrBiYxCt26HaWFUCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T19:28:03Z"
    mac: ENC[AES256_GCM,data:+UmjAV/vQits5nB+6G2+3mZYZ3ZwJWsLX/ACv41wSKgasVnBxN3jkKTq+3DTfwI6ecIZ4qQsK3xkdkUnkTi2LLvrS1wzbDtKUfPmUrFxmOhZsPoFuwQMqWiDMYYM8ZaPr8YdXbC8FSVz14CjvjLUxbzE2i9YRQhIlB1scnLsEWQ=,iv:es4LAkeaH2W6FP+YCtedETtci3ruVVsoE5VWDKajo+4=,tag:4Uuh3sJVRw5Fpzno75wHZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
