apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-users
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:NqYnKVcxLBIY4mqyk+gJNYftKBpkcXHmVjjQkxNhz5mBE63BKd+eW75rC2KgB1x5l+hp08A=,iv:ZRTSOv5KpMHT0pRN7SJNuZ9kbr0ukVL5r986AlLcSOs=,tag:Ht33G5If73iod3WdjvmbNA==,type:str]
sops:
    age:
        - recipient: age1rn9025gh9wcfwwuvde22hjhwle66w6qxrz6raxl28ed9r0rwsd0s5zd8fv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6U205VEpkYzdFNjdhZ1Av
            UGdqbHMvYUJHM1hJRGZKU3BueEdWL3QwYUNBCjJmY1UrenExVVZzYlNHUkFlU1dZ
            UVdKNUdaM3JUd0JGMGYyY0VjTnB0TGcKLS0tIGg1RlFYUFVHZUlZcUdWTWdrK2hz
            Qmx0elA4Wjk3ZmlVaUxhY3RjK2tpYk0KHG3A3srSU5czNRFW5gUfWJw3rQqROnSC
            HFvcNX4WeWpPniQDqFvy2c8W4Q7u6Q6+ubhj1BFmFC0j/a26LEzefQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-13T11:55:23Z"
    mac: ENC[AES256_GCM,data:iYqv8MouAd/Cddsph9FyNRvlwbF+mR9c8wFNtw6U6jivbMf+DSd163vGLtMenyUE4MzJ6vCO2WJprAGgnyklnQOY1Ln4Uw1HYA6crcbCVSsmD3cmMCAGmETTRBcSvmzWfGGK33rdvcaLznarxAbjfkadx0oCUTqkemsnFkf9vKE=,iv:FjTjUhCTCh+tTMihBDUccA6hU83o9d1JZwUhaEgjOUI=,tag:6GfFlsPTJtlCsMTJAgb0xw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
