apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-users
type: Opaque
stringData:
    users: ENC[AES256_GCM,data:PHoXFOLyJUnsNk4IEKFQ68z0I+ajhLen1iDT2593Ih0xQ3mHADtdoHqdcqyx1M17oOf2fTPCEj/5LlwfwwteZCfhmsTMINFU8/sVFwJJOH6jgUnTVKK3JkYMMzPyNYUn6U3NgKcH1WoqQhq9gFefQrSSmZNj+olg5WlffdUtDNbn9ZRJ8TcEaoB1lDvJ8dSujK2nj7+41gtfrqD1aRlDY4D3PmFFikqNJ2W6DfTBxHrhMeSCDGN4NP2LpmpLFmS/sJp7pmssxQQUN3HooXHQOxxjsks+Wwir2UPNjccUNozcElt66gjbrHWQKsl4rjHMu0h/6x600p7FVrXVbcaefk/DTgKCBzfGZKpPBnsK/dwZdUCSsoa6HmJc64B8cPQ4e1woYG+Um4IsghZqdoaTeH5qbP+qdxUv+5LUHB3sV2PyRT6vvRsg9wy2rcsd7JvS0Jx36nBErGKfkHHjZNdrq3UFxB51FG9vY8f0qt9umdr8GSneFTHlCoOlgwvy+/KbdFHZXz6nEhD5u4cwWAIuWuQmhMflL02B+WrI3/pmiiFUt83Uy4u4f2xcauvuooHL++yZp4A5pq7t6VKdtsu83oiLp66qDpdn5mWQIEnd14xSeEJKjDgl07SaecAwoTDZwMpXBGj1af23V1sXoqOaEEVaUXaZx9zYsvh71hbMl05LhIkQSM7IQc2JIDlDsGLIFfrm4coK5yoqdk+IVDBe3QqJEP+ORUw+yTntpTtABaWCpZxeitLIp2joneipiGB7qkWVZjagcMmg8KQ7O5U=,iv:3YNMxsUZhJlooCu3+PGmw/EIrCHFjgGtu9Cp4vELjHc=,tag:VmPAdUBWGHcl9UCdfi9gaw==,type:str]
sops:
    age:
        - recipient: age1rn9025gh9wcfwwuvde22hjhwle66w6qxrz6raxl28ed9r0rwsd0s5zd8fv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRUZkZ1RqbjBSRnFvSzJk
            MExlL1kyZ1ZnK1hqRFU1R1p0MUNxK1Z2WUVFCm5JcHNCcUNqckI0b2ljRVNqdUFR
            UVpvRXU0ayswZnRpNTNETVdqaWlRMkkKLS0tIGNMNU9Vck9uYnl1czdQeDhoZHRC
            OW95Z1pmcG9NVStOTkhSc0M5TzBBcHMK/e4WlCeYL5oKMIqXoFOS02Psban+I7fm
            jKo/tJ6ykU4CZhL3eSAbDzRh7G3LhG2sMF9z9XIiaps2hvywO6+9jQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T08:05:00Z"
    mac: ENC[AES256_GCM,data:Iyr2L/dv1s0Wwuqpe+3cdjgPKIYwXg9Z0up3ayZStndHiUeljmabz6VXuMlA5SpTdInTqYx40wB3gC7C//4wEdJy5Pm7p01wGWWynna3/hL5ox5a3XV+SCkjU7N8lG05FIuTwZkjUld6zGUdHC1CPai1teVWpayD7OJL9oVUSvw=,iv:Wz3YeOygtV8YJoycpqANKpcpki5JecyMXdY62xKiZiY=,tag:KGmthxpPwJkmbo3GS8f7gA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
